// ============================================================================
// softmax_engine.sv — Online Softmax Hardware Engine
// ============================================================================
// Computes attention weights P = softmax(S/√d) using FlashAttention's
// online softmax algorithm. Maintains running state (m, l) across KV tiles.
//
// Algorithm (per row i, TILE_ROWS=16 parallel):
//   1. Scale:  S_scaled = S_block / sqrt(HEAD_DIM)            [fp32 multiply]
//   2. RowMax: row_max = max(S_scaled across TILE_COLS)       [reduction tree]
//   3. Update: m_new = max(m_old, row_max)
//   4. Correct: correction = exp(m_old - m_new)              [EXP LUT, 1 cycle]
//   5. P:      P = exp(S_scaled - m_new)                     [EXP LUT, 1 cycle]
//   6. RowSum: row_sum = sum(P across TILE_COLS)             [reduction tree]
//   7. Update: l_new = l_old * correction + row_sum
//   8. Output: P_tile valid (streamed to MAC Phase B)
//
// EXP LUT: 1024-entry fp32 ROM, [-8, 0] range, linear interpolation.
//   Precision: < 0.1% relative error.
//   Resource: 1 BRAM (18Kb).
//
// Correspondence with Golden Model:
//   Python: attention_golden.py::OnlineSoftmaxState
//   Python: attention_golden.py::build_exp_lut(), exp_lut_lookup()
//
// VCS compatibility: Uses integer (not int) for all always_ff loop variables.
// ============================================================================

module softmax_engine
  import attn_pkg::*;
(
    input  logic                           clk,
    input  logic                           rst_n,

    // --- S_tile Input (from MAC Phase A) ---
    input  logic                           s_valid,
    input  logic [FP32_W-1:0]              s_data [TILE_ROWS][TILE_COLS],

    // --- Control ---
    input  logic                           kv_tile_first,  // init m/l for new Q tile
    input  logic                           kv_tile_last,   // trigger final norm

    // --- Causal Masking (decoder-only autoregressive) ---
    input  logic                           causal_mask_en, // enable causal masking
    input  logic [15:0]                    q_tile_start,   // absolute Q row start index
    input  logic [15:0]                    kv_tile_start,  // absolute K col start index

    // --- Running State (maintained across KV tiles) ---
    output logic [FP32_W-1:0]              m_state [TILE_ROWS],   // running max per row
    output logic [FP32_W-1:0]              l_state [TILE_ROWS],   // running sum per row

    // --- P_tile Output (to MAC Phase B) ---
    output logic                           p_valid,
    output logic [FP32_W-1:0]              p_data [TILE_ROWS][TILE_COLS],

    // --- Correction factors (to psum_accum for O_acc update) ---
    output logic [FP32_W-1:0]              correction [TILE_ROWS],

    // --- Done pulse ---
    output logic                           done
);

  // ==================================================================
  // EXP LUT ROM (1024 × fp32)
  // ==================================================================
  // Generated by Python golden model: build_exp_lut()
  // Range: [-8.0, 0.0], 1024 entries, linear interpolation between entries.
  //
  // For synthesis: infer as BRAM ROM (read-only, initialized at bitstream load).
  // For simulation: loaded from $readmemh or generated inline.

  localparam int LUT_DEPTH = 1024;
  logic [FP32_W-1:0] exp_lut [0:LUT_DEPTH-1];

  // LUT initialization via $readmemh (load from hex file at sim start)
  initial begin
    integer fd;
    fd = $fopen("data/exp_lut.hex", "r");
    if (fd) begin
      for (int li = 0; li < LUT_DEPTH; li++)
        $fscanf(fd, "%h", exp_lut[li]);
      $fclose(fd);
    end else begin
      // Fallback: load from golden model inline (generated once)
      // Using hardcoded LUT from Python build_exp_lut() for standalone sim
      $display("WARNING: data/exp_lut.hex not found. Run python_godel export first.");
      $display("  python python_godel/attention_golden.py --export-tb-data --module softmax");
    end
  end

  // ==================================================================
  // EXP LUT Lookup Function
  // ==================================================================
  // Input:  x in fp32, range [-8, 0] (clamped outside)
  // Output: exp(x) in fp32
  // Latency: 1 cycle (combinational lookup + interpolation)
  function automatic shortreal exp_lookup(input shortreal x);
    shortreal x_clamped;
    shortreal idx_float, frac;
    integer idx_lo, idx_hi;
    shortreal v_lo, v_hi;

    // Clamp to [-8, 0]
    if (x < -8.0)      x_clamped = -8.0;
    else if (x > 0.0)  x_clamped = 0.0;
    else               x_clamped = x;

    // Map [-8, 0] → [0, 1023]
    idx_float = (x_clamped + 8.0) * shortreal'(LUT_DEPTH - 1) / 8.0;
    idx_lo = integer'(idx_float);
    idx_hi = idx_lo + 1;
    if (idx_hi >= LUT_DEPTH) idx_hi = LUT_DEPTH - 1;

    frac = idx_float - shortreal'(idx_lo);

    v_lo = $bitstoshortreal(exp_lut[idx_lo]);
    v_hi = $bitstoshortreal(exp_lut[idx_hi]);

    // Linear interpolation
    exp_lookup = v_lo + frac * (v_hi - v_lo);
  endfunction

  // ==================================================================
  // Pipeline Registers
  // ==================================================================
  // Stage 1 → Stage 2 pipeline

  logic                           s_valid_r;
  logic [FP32_W-1:0]              s_data_r [TILE_ROWS][TILE_COLS];
  logic                           kv_tile_first_r, kv_tile_last_r;
  logic                           causal_mask_en_r;
  logic [15:0]                    q_tile_start_r, kv_tile_start_r;

  // Stage 1 computed values
  shortreal row_max_s1   [TILE_ROWS];
  shortreal m_old_s1     [TILE_ROWS];
  shortreal S_scaled     [TILE_ROWS][TILE_COLS];

  // Stage 2 outputs
  shortreal P_shortreal  [TILE_ROWS][TILE_COLS];
  shortreal m_new        [TILE_ROWS];
  shortreal l_new        [TILE_ROWS];
  shortreal correction_s [TILE_ROWS];

  // ==================================================================
  // Stage 1: Scale + RowMax + Max Update
  // ==================================================================
  // Computes: S_scaled = S * (1/sqrt(HEAD_DIM)), row_max per row

  // sqrt(128) ≈ 11.3137, 1/sqrt(128) ≈ 0.088388 (from pkg: INV_SQRT_D_FP32)

  always_comb begin
    integer ri, ci;
    for (ri = 0; ri < TILE_ROWS; ri++) begin
      // Find row max over TILE_COLS
      row_max_s1[ri] = -1.0e30; // -inf approximation
      for (ci = 0; ci < TILE_COLS; ci++) begin
        S_scaled[ri][ci] = $bitstoshortreal(s_data[ri][ci])
                         * $bitstoshortreal(INV_SQRT_D_FP32);
        if (S_scaled[ri][ci] > row_max_s1[ri])
          row_max_s1[ri] = S_scaled[ri][ci];
      end
    end
  end

  // ==================================================================
  // Pipeline Stage 1 → 2 (registered)
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      s_valid_r <= 1'b0;
      kv_tile_first_r <= 1'b0;
      kv_tile_last_r  <= 1'b0;
      causal_mask_en_r <= 1'b0;
      q_tile_start_r   <= 16'd0;
      kv_tile_start_r  <= 16'd0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= 0.0;
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= 32'd0;
      end
    end else begin
      s_valid_r <= s_valid;
      kv_tile_first_r <= kv_tile_first;
      kv_tile_last_r  <= kv_tile_last;
      causal_mask_en_r <= causal_mask_en;
      q_tile_start_r   <= q_tile_start;
      kv_tile_start_r  <= kv_tile_start;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= $bitstoshortreal(m_state[ri]);
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= s_data[ri][ci];
      end
    end
  end

  // ==================================================================
  // Stage 2: Online Softmax Update
  // ==================================================================
  // For each row: compute m_new, correction, P, l_new

  always_comb begin
    integer ri, ci;
    shortreal m_old_val, row_max_val, m_new_val;
    shortreal correction_val, l_old_val;
    shortreal row_exp_sum;

    for (ri = 0; ri < TILE_ROWS; ri++) begin
      m_old_val = m_old_s1[ri];
      row_max_val = row_max_s1[ri];

      // Init on first KV tile: m starts at -inf, l at 0
      if (s_valid_r && kv_tile_first_r) begin
        m_old_val = -1.0e30;
        l_old_val = 0.0;  // use local variable, not output port
      end else begin
        l_old_val = $bitstoshortreal(l_state[ri]);
      end

      // Update running max
      if (m_old_val > row_max_val)
        m_new_val = m_old_val;
      else
        m_new_val = row_max_val;

      // Correction factor: exp(m_old - m_new)
      correction_val = exp_lookup(m_old_val - m_new_val);
      correction_s[ri] = correction_val;

      // Running max output
      m_new[ri] = m_new_val;

      // Compute P and row sum
      row_exp_sum = 0.0;
      for (ci = 0; ci < TILE_COLS; ci++) begin
        shortreal S_shifted, P_val;
        S_shifted = $bitstoshortreal(s_data_r[ri][ci])                         * $bitstoshortreal(INV_SQRT_D_FP32)
                    - m_new_val;

        // Causal masking: mask out future positions (q_pos < k_pos → -inf)
        if (causal_mask_en_r) begin
          if ((q_tile_start_r + 16'(ri)) < (kv_tile_start_r + 16'(ci)))
            S_shifted = -100.0;  // effectively -inf, exp(-100) ≈ 3.7e-44 ≈ 0
        end

        P_val = exp_lookup(S_shifted);
        P_shortreal[ri][ci] = P_val;
        row_exp_sum = row_exp_sum + P_val;
      end

      // Update running sum: l_new = l_old * correction + row_exp_sum
      l_new[ri] = l_old_val * correction_val + row_exp_sum;
    end
  end

  // ==================================================================
  // Output Register Stage
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      p_valid <= 1'b0;
      done    <= 1'b0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_state[ri]   <= 32'hFF800000;  // -inf in fp32
        l_state[ri]   <= 32'd0;
        correction[ri] <= 32'd0;
        for (ci = 0; ci < TILE_COLS; ci++)
          p_data[ri][ci] <= 32'd0;
      end
    end else begin
      p_valid <= s_valid_r;  // 2-cycle pipeline delay from s_valid
      done    <= s_valid_r && kv_tile_last_r;

      if (s_valid_r) begin
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]   <= $shortrealtobits(m_new[ri]);
          l_state[ri]   <= $shortrealtobits(l_new[ri]);
          correction[ri] <= $shortrealtobits(correction_s[ri]);
          for (ci = 0; ci < TILE_COLS; ci++)
            p_data[ri][ci] <= $shortrealtobits(P_shortreal[ri][ci]);
        end
      end
    end
  end

endmodule
