// ============================================================================
// softmax_engine.sv — Online Softmax Hardware Engine
// ============================================================================
// Computes attention weights P = softmax(S/√d) using FlashAttention's
// online softmax algorithm. Maintains running state (m, l) across KV tiles.
//
// Algorithm (per row i, TILE_ROWS=16 parallel):
//   1. Scale:  S_scaled = S_block / sqrt(HEAD_DIM)            [fp32 multiply]
//   2. RowMax: row_max = max(S_scaled across TILE_COLS)       [reduction tree]
//   3. Update: m_new = max(m_old, row_max)
//   4. Correct: correction = exp(m_old - m_new)              [EXP LUT, 1 cycle]
//   5. P:      P = exp(S_scaled - m_new)                     [EXP LUT, 1 cycle]
//   6. RowSum: row_sum = sum(P across TILE_COLS)             [reduction tree]
//   7. Update: l_new = l_old * correction + row_sum
//   8. Output: P_tile valid (streamed to MAC Phase B)
//
// EXP LUT: 1024-entry fp32 ROM, [-8, 0] range, linear interpolation.
//   Precision: < 0.1% relative error.
//   Resource: 1 BRAM (18Kb).
//
// Correspondence with Golden Model:
//   Python: attention_golden.py::OnlineSoftmaxState
//   Python: attention_golden.py::build_exp_lut(), exp_lut_lookup()
//
// VCS compatibility: Uses integer (not int) for all always_ff loop variables.
// ============================================================================

module softmax_engine
  import attn_pkg::*;
(
    input  logic                           clk,
    input  logic                           rst_n,

    // --- S_tile Input (from MAC Phase A) ---
    input  logic                           s_valid,
    output logic                           s_ready,
    input  logic [FP32_W-1:0]              s_data [TILE_ROWS][TILE_COLS],

    // --- Control ---
    input  logic                           kv_tile_first,  // init m/l for new Q tile
    input  logic                           kv_tile_last,   // trigger final norm

    // --- Causal Masking (decoder-only autoregressive) ---
    input  logic                           causal_mask_en, // enable causal masking
    input  logic [15:0]                    q_tile_start,   // absolute Q row start index
    input  logic [15:0]                    kv_tile_start,  // absolute K col start index
    input  logic [4:0]                     active_rows,    // valid rows in this 16x16 block
    input  logic [4:0]                     active_cols,    // valid cols in this 16x16 block

    // --- Optional State Context Load (for time-multiplexed microtiles) ---
    input  logic                           state_load,
    input  logic [FP32_W-1:0]              state_m_in [TILE_ROWS],
    input  logic [FP32_W-1:0]              state_l_in [TILE_ROWS],

    // --- Running State (maintained across KV tiles) ---
    output logic [FP32_W-1:0]              m_state [TILE_ROWS],   // running max per row
    output logic [FP32_W-1:0]              l_state [TILE_ROWS],   // running sum per row

    // --- P_tile Output (to MAC Phase B) ---
    output logic                           p_valid,
    output wire [FP32_W-1:0]               p_data [TILE_ROWS][TILE_COLS],

    // --- Correction factors (to psum_accum for O_acc update) ---
    output logic [FP32_W-1:0]              correction [TILE_ROWS],

    // --- Done pulse ---
    output logic                           done
);

  (* keep = "true" *) logic unused_kv_tile_last;
  assign unused_kv_tile_last = &{1'b0, kv_tile_last};

  // ==================================================================
  // EXP LUT ROM (1024 × fp32)
  // ==================================================================
  // Generated by Python golden model: build_exp_lut()
  // Range: [-8.0, 0.0], 1024 entries, linear interpolation between entries.
  //
  // For synthesis: infer as BRAM ROM (read-only, initialized at bitstream load).
  // For simulation: loaded from $readmemh or generated inline.

  localparam int LUT_DEPTH = 1024;
  localparam logic [31:0] FP32_NEG_INF_BITS = 32'hFF80_0000;
  localparam logic [31:0] FP32_ZERO_BITS    = 32'h0000_0000;
  localparam logic [31:0] FP32_ONE_BITS     = 32'h3F80_0000;
  localparam logic [31:0] FP32_NEG_EIGHT_BITS = 32'hC100_0000;
  localparam shortreal NEG_INF_SR    = -1.0e30;
  localparam shortreal NEG_EIGHT_SR  = -8.0;
  localparam shortreal ZERO_SR       = 0.0;
  localparam shortreal ONE_SR        = 1.0;
  localparam shortreal EIGHT_SR      = 8.0;
  (* rom_style = "block" *) logic [FP32_W-1:0] exp_lut [0:LUT_DEPTH-1];

`ifndef SYNTHESIS
  // The behavioral model is a two-stage pipeline and can accept a new block
  // whenever a context load is not taking priority.
  assign s_ready = !state_load;
  // LUT initialization for simulation. Try the local TB path first, then the
  // repo-relative path used by direct module compiles.
  initial begin
    integer fd;
    integer lut_scan_rc;
    lut_scan_rc = 0;
    fd = $fopen("data/exp_lut.hex", "r");
    if (fd == 0)
      fd = $fopen("VV/data/exp_lut.hex", "r");
    if (fd != 0) begin
      for (int li = 0; li < LUT_DEPTH; li++)
        lut_scan_rc = $fscanf(fd, "%h", exp_lut[li]);
      $fclose(fd);
    end else begin
      $display("WARNING: exp_lut.hex not found. Expected data/exp_lut.hex or VV/data/exp_lut.hex");
      $display("  python python_godel/attention_golden.py --export-tb-data --module softmax");
    end
  end
`else
  // Vivado can infer ROM contents from a direct readmemh on a project-added
  // memory-init file. Avoid fopen/fscanf, which synthesis ignores.
  initial begin
    $readmemh("exp_lut.hex", exp_lut);
  end
`endif

  // ==================================================================
  // EXP LUT Lookup Function
  // ==================================================================
  // Input: x in fp32. Values below -8 are truncated to zero; values above
  // zero saturate to one. This matches the Python golden-model contract.
  // Output: exp(x) in fp32
  // Latency: 1 cycle (combinational lookup + interpolation)
  function automatic shortreal exp_lookup(input shortreal x);
    /* verilator lint_off WIDTHEXPAND */
    shortreal idx_float, frac;
    integer idx_lo, idx_hi;
    shortreal v_lo, v_hi;

    if (x < NEG_EIGHT_SR) begin
      exp_lookup = ZERO_SR;
    end else if (x > ZERO_SR) begin
      exp_lookup = ONE_SR;
    end else begin
      // Map [-8, 0] -> [0, 1023].
      idx_float = (x + EIGHT_SR) * shortreal'(LUT_DEPTH - 1) / EIGHT_SR;
      idx_lo = integer'(idx_float);
      idx_hi = idx_lo + 1;
      if (idx_hi >= LUT_DEPTH) idx_hi = LUT_DEPTH - 1;

      frac = idx_float - shortreal'(idx_lo);
      v_lo = $bitstoshortreal(exp_lut[idx_lo]);
      v_hi = $bitstoshortreal(exp_lut[idx_hi]);
      exp_lookup = v_lo + frac * (v_hi - v_lo);
    end
    /* verilator lint_on WIDTHEXPAND */
  endfunction

  // ==================================================================
  // Pipeline Registers
  // ==================================================================
  // Stage 1 → Stage 2 pipeline

  logic                           s_valid_r;
  logic [FP32_W-1:0]              s_data_r [TILE_ROWS][TILE_COLS];
  logic [FP32_W-1:0]              p_data_reg [TILE_ROWS][TILE_COLS];
  logic                           kv_tile_first_r;
  logic                           causal_mask_en_r;
  logic [15:0]                    q_tile_start_r, kv_tile_start_r;
  logic [4:0]                     active_rows_r, active_cols_r;

  // Stage 1 computed values
  shortreal row_max_s1   [TILE_ROWS];
  shortreal m_old_s1     [TILE_ROWS];
  shortreal S_scaled     [TILE_ROWS][TILE_COLS];

  // Stage 2 outputs
  shortreal P_shortreal  [TILE_ROWS][TILE_COLS];
  shortreal m_new        [TILE_ROWS];
  shortreal l_new        [TILE_ROWS];
  shortreal correction_s [TILE_ROWS];

  // ==================================================================
  // Stage 1: Scale + RowMax + Max Update
  // ==================================================================
  // Computes: S_scaled = S * (1/sqrt(HEAD_DIM)), row_max per row

  // sqrt(128) ≈ 11.3137, 1/sqrt(128) ≈ 0.088388 (from pkg: INV_SQRT_D_FP32)

`ifndef SYNTHESIS
  for (genvar pgr = 0; pgr < TILE_ROWS; pgr++) begin : g_beh_p_data_row
    for (genvar pgc = 0; pgc < TILE_COLS; pgc++) begin : g_beh_p_data_col
      assign p_data[pgr][pgc] = p_data_reg[pgr][pgc];
    end
  end

  /* verilator lint_off SHORTREAL */
  /* verilator lint_off WIDTHEXPAND */
  /* verilator lint_off WIDTHTRUNC */
  always_comb begin
    integer ri, ci;
    integer active_rows_i, active_cols_i;
    logic row_valid, col_valid;
    active_rows_i = integer'(active_rows);
    active_cols_i = integer'(active_cols);
    for (ri = 0; ri < TILE_ROWS; ri++) begin
      row_valid = (ri < active_rows_i);
      row_max_s1[ri] = $bitstoshortreal(FP32_NEG_INF_BITS);
      for (ci = 0; ci < TILE_COLS; ci++) begin
        col_valid = (ci < active_cols_i);
        if (row_valid && col_valid) begin
          S_scaled[ri][ci] = $bitstoshortreal(s_data[ri][ci])
                           * $bitstoshortreal(INV_SQRT_D_FP32);
        end else begin
          S_scaled[ri][ci] = $bitstoshortreal(FP32_NEG_INF_BITS);
        end
        if (row_valid && col_valid && causal_mask_en) begin
          if ((q_tile_start + 16'(ri)) < (kv_tile_start + 16'(ci)))
            S_scaled[ri][ci] = $bitstoshortreal(FP32_NEG_INF_BITS);
        end
        if (S_scaled[ri][ci] > row_max_s1[ri])
          row_max_s1[ri] = S_scaled[ri][ci];
      end
    end
  end

  // ==================================================================
  // Pipeline Stage 1 → 2 (registered)
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      s_valid_r <= 1'b0;
      kv_tile_first_r <= 1'b0;
      causal_mask_en_r <= 1'b0;
      q_tile_start_r   <= 16'd0;
      kv_tile_start_r  <= 16'd0;
      active_rows_r    <= 5'd0;
      active_cols_r    <= 5'd0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= $bitstoshortreal(FP32_ZERO_BITS);
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= 32'd0;
      end
    end else begin
      s_valid_r <= s_valid && s_ready;
      kv_tile_first_r <= kv_tile_first;
      causal_mask_en_r <= causal_mask_en;
      q_tile_start_r   <= q_tile_start;
      kv_tile_start_r  <= kv_tile_start;
      active_rows_r    <= active_rows;
      active_cols_r    <= active_cols;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= $bitstoshortreal(m_state[ri]);
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= s_data[ri][ci];
      end
    end
  end

  // ==================================================================
  // Stage 2: Online Softmax Update
  // ==================================================================
  // For each row: compute m_new, correction, P, l_new

  always_comb begin
    integer ri, ci;
    integer active_rows_i, active_cols_i;
    logic row_valid, col_valid;
    logic masked;
    shortreal m_old_val, row_max_val, m_new_val;
    shortreal correction_val, l_old_val;
    shortreal row_exp_sum, S_shifted, P_val;
    active_rows_i = integer'(active_rows_r);
    active_cols_i = integer'(active_cols_r);
    masked = 1'b1;
    S_shifted = ZERO_SR;
    P_val = ZERO_SR;

    for (ri = 0; ri < TILE_ROWS; ri++) begin
      row_valid = (ri < active_rows_i);
      m_old_val = m_old_s1[ri];
      row_max_val = row_max_s1[ri];
      m_new_val = m_old_val;
      correction_val = ONE_SR;
      row_exp_sum = ZERO_SR;

      // Init on first KV tile: m starts at -inf, l at 0
      if (s_valid_r && kv_tile_first_r) begin
        m_old_val = NEG_INF_SR;
        l_old_val = ZERO_SR;  // use local variable, not output port
      end else begin
        l_old_val = $bitstoshortreal(l_state[ri]);
      end

      correction_s[ri] = ONE_SR;
      m_new[ri] = m_old_val;
      l_new[ri] = l_old_val;
      for (ci = 0; ci < TILE_COLS; ci++)
        P_shortreal[ri][ci] = ZERO_SR;

      if (!row_valid) begin
        col_valid = 1'b0;
      end else begin
        // Update running max
        if (m_old_val > row_max_val)
          m_new_val = m_old_val;
        else
          m_new_val = row_max_val;

        // Correction factor: exp(m_old - m_new)
        if (s_valid_r && kv_tile_first_r)
          correction_val = ZERO_SR;
        else
          correction_val = exp_lookup(m_old_val - m_new_val);
        correction_s[ri] = correction_val;

        // Running max output
        m_new[ri] = m_new_val;

        // Compute P and row sum
        for (ci = 0; ci < TILE_COLS; ci++) begin
          S_shifted = ZERO_SR;
          P_val = ZERO_SR;
          masked = 1'b1;
          col_valid = (ci < active_cols_i);
          masked = !col_valid;
          S_shifted = $bitstoshortreal(s_data_r[ri][ci]) * $bitstoshortreal(INV_SQRT_D_FP32)
                      - m_new_val;

          // Causal masking: mask out future positions (q_pos < k_pos → -inf)
          if (causal_mask_en_r && col_valid) begin
            if ((q_tile_start_r + 16'(ri)) < (kv_tile_start_r + 16'(ci)))
              masked = 1'b1;
          end

          if (masked)
            P_val = ZERO_SR;
          else
            P_val = exp_lookup(S_shifted);
          P_shortreal[ri][ci] = P_val;
          row_exp_sum = row_exp_sum + P_val;
        end

        // Update running sum: l_new = l_old * correction + row_exp_sum
        if (s_valid_r && kv_tile_first_r)
          l_new[ri] = row_exp_sum;
        else
          l_new[ri] = l_old_val * correction_val + row_exp_sum;
      end
    end
  end

  // ==================================================================
  // Output Register Stage
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      p_valid <= 1'b0;
      done    <= 1'b0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_state[ri]   <= 32'hFF800000;  // -inf in fp32
        l_state[ri]   <= 32'd0;
        correction[ri] <= 32'd0;
        for (ci = 0; ci < TILE_COLS; ci++)
          p_data_reg[ri][ci] <= 32'd0;
      end
    end else begin
      p_valid <= s_valid_r;  // 2-cycle pipeline delay from s_valid
      done    <= s_valid_r;

      if (state_load) begin
        p_valid <= 1'b0;
        done    <= 1'b0;
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]   <= state_m_in[ri];
          l_state[ri]   <= state_l_in[ri];
          correction[ri] <= 32'd0;
        end
      end else if (s_valid_r) begin
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]   <= $shortrealtobits(m_new[ri]);
          l_state[ri]   <= $shortrealtobits(l_new[ri]);
          correction[ri] <= $shortrealtobits(correction_s[ri]);
          for (ci = 0; ci < TILE_COLS; ci++)
            p_data_reg[ri][ci] <= $shortrealtobits(P_shortreal[ri][ci]);
        end
      end
    end
  end


  /* verilator lint_on WIDTHTRUNC */
  /* verilator lint_on WIDTHEXPAND */
  /* verilator lint_on SHORTREAL */
`else
  typedef enum logic [4:0] {
    SM_IDLE        = 5'd0,
    SM_SCALE_MAX   = 5'd1,
    SM_MAX_UPDATE  = 5'd2,
    SM_CORR_SHIFT  = 5'd3,
    SM_CORR_LOOKUP = 5'd4,
    SM_P_SHIFT     = 5'd5,
    SM_P_LOOKUP    = 5'd6,
    SM_P_ACCUM     = 5'd7,
    SM_L_MUL       = 5'd8,
    SM_L_ADD       = 5'd9,
    SM_WRITE       = 5'd10,
    SM_SCALE_DRAIN = 5'd11,
    SM_P_PIPE      = 5'd12,
    SM_CORR_INDEX  = 5'd13,
    SM_CORR_LUT    = 5'd14,
    SM_CORR_DELTA  = 5'd15,
    SM_CORR_MUL    = 5'd16,
    SM_CORR_ADD    = 5'd17
  } sm_state_t;

  sm_state_t sm_state;
  assign s_ready = (sm_state == SM_IDLE) && !state_load;
  logic [4:0] sm_row_idx;
  logic [4:0] sm_col_idx;
  logic [31:0] sm_row_sum_acc;
  logic [31:0] sm_row_sum [TILE_ROWS];
  logic [31:0] sm_shifted_pipe;
  logic [31:0] sm_p_pipe;
  logic [31:0] sm_corr_shift_pipe;
  logic [31:0] sm_l_corr_product;
  logic        sm_masked_pipe;
  logic        sm_scale_valid;
  logic [4:0]  sm_scale_row_pipe;
  logic [4:0]  sm_scale_col_pipe;
  logic [31:0] sm_scale_value_pipe;
  logic        sm_scale_masked_pipe;
  localparam integer EXP_PREP_W = 38;  // mode[1:0] + index[9:0] + rem[25:0]
  localparam integer EXP_QUANT_W = 30; // mode[1:0] + signed Q8.23[27:0]
  logic        sm_p_shift_valid;
  logic [4:0]  sm_p_shift_row;
  logic [4:0]  sm_p_shift_col;
  logic        sm_exp_quant_valid;
  logic [4:0]  sm_exp_quant_row;
  logic [4:0]  sm_exp_quant_col;
  logic [EXP_QUANT_W-1:0] sm_exp_quant;
  logic        sm_exp_req_valid;
  logic [4:0]  sm_exp_req_row;
  logic [4:0]  sm_exp_req_col;
  logic [EXP_PREP_W-1:0] sm_exp_req;
  logic        sm_exp_lut_valid;
  logic [4:0]  sm_exp_lut_row;
  logic [4:0]  sm_exp_lut_col;
  logic [1:0]  sm_exp_lut_mode;
  logic [9:0]  sm_exp_lut_idx;
  logic [25:0] sm_exp_lut_rem;
  logic        sm_exp_frac_valid;
  logic [4:0]  sm_exp_frac_row;
  logic [4:0]  sm_exp_frac_col;
  logic [1:0]  sm_exp_frac_mode;
  logic [31:0] sm_exp_frac_fp;
  logic [31:0] sm_exp_frac_lut_lo;
  logic [31:0] sm_exp_frac_lut_hi;
  logic        sm_exp_delta_valid;
  logic [4:0]  sm_exp_delta_row;
  logic [4:0]  sm_exp_delta_col;
  logic [1:0]  sm_exp_delta_mode;
  logic [31:0] sm_exp_delta_frac_fp;
  logic [31:0] sm_exp_delta_lut_lo;
  logic [31:0] sm_exp_delta;
  logic        sm_exp_mul_valid;
  logic [4:0]  sm_exp_mul_row;
  logic [4:0]  sm_exp_mul_col;
  logic [1:0]  sm_exp_mul_mode;
  logic [31:0] sm_exp_mul_lut_lo;
  logic [31:0] sm_exp_mul_product;
  logic        sm_p_lookup_valid;
  logic [4:0]  sm_p_lookup_row;
  logic [4:0]  sm_p_lookup_col;
  logic        sm_p_issue_done;
  localparam logic [4:0] SM_TILE_ROWS_LAST = 5'(TILE_ROWS - 1);
  localparam logic [4:0] SM_TILE_COLS_LAST = 5'(TILE_COLS - 1);
  logic [31:0] sm_m_old [TILE_ROWS];
  logic [31:0] sm_l_old [TILE_ROWS];
  logic [31:0] sm_row_max [TILE_ROWS];
  logic [31:0] sm_m_new [TILE_ROWS];
  logic [31:0] sm_l_new [TILE_ROWS];
  logic [31:0] sm_corr [TILE_ROWS];
  logic [31:0] sm_p [TILE_ROWS][TILE_COLS];
  logic [31:0] sm_scaled [TILE_ROWS][TILE_COLS];
  logic        sm_masked [TILE_ROWS][TILE_COLS];

  for (genvar pgr = 0; pgr < TILE_ROWS; pgr++) begin : g_synth_p_data_row
    for (genvar pgc = 0; pgc < TILE_COLS; pgc++) begin : g_synth_p_data_col
      if (SOFTMAX_P_OUTPUT_DIRECT && SOFTMAX_P_INPLACE) begin : g_direct
        if (SOFTMAX_SCORE_INPLACE) begin : g_score_scratch
          assign p_data[pgr][pgc] = s_data_r[pgr][pgc];
        end else begin : g_scaled_scratch
          assign p_data[pgr][pgc] = sm_scaled[pgr][pgc];
        end
      end else begin : g_registered
        assign p_data[pgr][pgc] = p_data_reg[pgr][pgc];
      end
    end
  end

  function automatic logic [31:0] q23_to_fp32(input integer value);
    integer bit_idx;
    integer exponent_value;
    logic [22:0] mantissa_value;
    integer residual;
    begin
      if (value <= 0) begin
        q23_to_fp32 = 32'd0;
      end else begin
        bit_idx = 22;
        while ((bit_idx > 0) && !value[bit_idx])
          bit_idx = bit_idx - 1;
        residual = value - (1 <<< bit_idx);
        mantissa_value = 23'd0;
        if (bit_idx < 23)
          mantissa_value = residual <<< (23 - bit_idx);
        exponent_value = 127 + bit_idx - 23;
        q23_to_fp32 = {1'b0, exponent_value[7:0], mantissa_value};
      end
    end
  endfunction

  function automatic longint signed fp32_to_q8_23(input logic [31:0] value_bits);
    logic        sign_value;
    logic [7:0]  exponent_value;
    logic [23:0] mantissa_value;
    integer      shift_value;
    longint signed scaled_value;
    begin
      if (fp32_is_zero(value_bits)) begin
        fp32_to_q8_23 = 0;
      end else begin
        sign_value = value_bits[31];
        exponent_value = value_bits[30:23];
        mantissa_value = {1'b1, value_bits[22:0]};
        shift_value = integer'(exponent_value) - 127;
        scaled_value = longint'({24'd0, mantissa_value});
        if (shift_value >= 0)
          scaled_value = scaled_value <<< shift_value;
        else
          scaled_value = scaled_value >>> (-shift_value);
        fp32_to_q8_23 = sign_value ? -scaled_value : scaled_value;
      end
    end
  endfunction

  function automatic logic [31:0] q26_to_fp32(input longint signed value);
    integer bit_idx;
    integer exponent_value;
    longint signed residual;
    logic [22:0] mantissa_value;
    begin
      if (value <= 0) begin
        q26_to_fp32 = 32'd0;
      end else begin
        bit_idx = 25;
        while ((bit_idx > 0) && !value[bit_idx])
          bit_idx = bit_idx - 1;
        residual = value - (64'sd1 <<< bit_idx);
        if (bit_idx < 23)
          mantissa_value = residual <<< (23 - bit_idx);
        else
          mantissa_value = residual >>> (bit_idx - 23);
        exponent_value = 127 + bit_idx - 26;
        q26_to_fp32 = {1'b0, exponent_value[7:0], mantissa_value};
      end
    end
  endfunction

  function automatic logic [31:0] exp_lookup_bits(input logic [31:0] x);
    longint signed x_q;
    logic [63:0] idx_num;
    logic [22:0] frac_num;
    logic [31:0] frac_fp;
    logic [31:0] lut_lo;
    logic [31:0] lut_hi;
    logic [31:0] lut_delta;
    logic [31:0] lut_interp;
    longint signed idx_num_signed;
    integer idx;
    longint signed rem;

    begin
      if (fp32_gt(FP32_NEG_EIGHT_BITS, x)) begin
        exp_lookup_bits = FP32_ZERO_BITS;
      end else if (fp32_gt(x, FP32_ZERO_BITS)) begin
        exp_lookup_bits = FP32_ONE_BITS;
      end else begin
        x_q = fp32_to_q8_23(x);
        idx_num_signed = x_q + 67108864;
        if (idx_num_signed < 0)
          idx_num_signed = 0;
        else if (idx_num_signed > 67108864)
          idx_num_signed = 67108864;
        idx_num = (idx_num_signed <<< 10) - idx_num_signed;
        // x_q is Q8.23 and the LUT spans eight units.  The interpolation
        // coordinate therefore uses Q8.26: idx = ((x + 8) * 1023) / 2^26.
        idx = integer'(idx_num >>> 26);
        rem = longint'(idx_num - (longint'(idx) <<< 26));
`ifdef LARA_SOFTMAX_FUNC_DEBUG
        if ((x == 32'hbc315c62) || (x == 32'hbc822a40) ||
            (x == 32'h00000000))
          $display("EXP_DEBUG x=%h xq=%0d idxnum=%0d idx=%0d rem=%0d",
                   x, x_q, idx_num_signed, idx, rem);
`endif
        if (idx < 0) idx = 0;
        else if (idx >= LUT_DEPTH) idx = LUT_DEPTH - 1;
        if (idx == LUT_DEPTH - 1) begin
          exp_lookup_bits = exp_lut[idx];
        end else begin
          frac_num = rem[25:3];
          frac_fp = q26_to_fp32(rem);
          lut_lo = exp_lut[idx];
          lut_hi = exp_lut[idx + 1];
          lut_delta = fp32_sub(lut_hi, lut_lo);
          lut_interp = fp32_add(lut_lo, fp32_mul(lut_delta, frac_fp));
          exp_lookup_bits = lut_interp;
        end
      end
    end
  endfunction

  // Timing-optimized equivalent of exp_lookup_bits.  The lookup is split into
  // quantization, index calculation, and interpolation pipeline stages.
  function automatic logic [EXP_QUANT_W-1:0] exp_lookup_quantize(
      input logic [31:0] x
  );
    longint signed x_q;
    logic [1:0] mode;
    logic signed [27:0] x_q_bits;
    begin
      mode = 2'd2;
      x_q_bits = 28'sd0;
      if (fp32_gt(FP32_NEG_EIGHT_BITS, x)) begin
        mode = 2'd0;  // below LUT range
      end else if (fp32_gt(x, FP32_ZERO_BITS)) begin
        mode = 2'd1;  // positive input saturates to one
      end else begin
        x_q = fp32_to_q8_23(x);
        x_q_bits = x_q;
      end
      exp_lookup_quantize = {mode, x_q_bits};
    end
  endfunction

  function automatic logic [EXP_PREP_W-1:0] exp_lookup_index(
      input logic [EXP_QUANT_W-1:0] quantized
  );
    longint signed x_q;
    longint signed idx_num_signed;
    longint signed rem;
    logic [63:0] idx_num;
    logic [1:0] mode;
    logic [9:0] idx_bits;
    logic [25:0] rem_bits;
    begin
      mode = quantized[29:28];
      x_q = $signed(quantized[27:0]);
      idx_bits = 10'd0;
      rem_bits = 26'd0;
      if (mode == 2'd2) begin
        idx_num_signed = x_q + 67108864;
        if (idx_num_signed < 0)
          idx_num_signed = 0;
        else if (idx_num_signed > 67108864)
          idx_num_signed = 67108864;
        idx_num = (idx_num_signed <<< 10) - idx_num_signed;
        idx_bits = integer'(idx_num >>> 26);
        rem = longint'(idx_num - (longint'(idx_bits) <<< 26));
        if (idx_bits >= LUT_DEPTH)
          idx_bits = 10'(LUT_DEPTH - 1);
        rem_bits = rem[25:0];
      end
      exp_lookup_index = {mode, idx_bits, rem_bits};
    end
  endfunction

  function automatic logic [31:0] exp_lookup_finish(
      input logic [1:0] mode,
      input logic [9:0] idx,
      input logic [25:0] rem
  );
    logic [31:0] frac_fp;
    logic [31:0] lut_lo;
    logic [31:0] lut_hi;
    logic [31:0] lut_delta;
    begin
      case (mode)
        2'd0: exp_lookup_finish = FP32_ZERO_BITS;
        2'd1: exp_lookup_finish = FP32_ONE_BITS;
        default: begin
          if (idx == LUT_DEPTH - 1) begin
            exp_lookup_finish = exp_lut[idx];
          end else begin
            frac_fp = q26_to_fp32(longint'(rem));
            lut_lo = exp_lut[idx];
            lut_hi = exp_lut[idx + 1'b1];
            lut_delta = fp32_sub(lut_hi, lut_lo);
            exp_lookup_finish = fp32_add(
                lut_lo, fp32_mul(lut_delta, frac_fp)
            );
          end
        end
      endcase
    end
  endfunction

  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    logic        row_valid;
    logic        col_valid;
    logic        masked;
    integer      q_pos;
    integer      kv_pos;
    logic [31:0] scaled_val;
    logic [31:0] row_max_next;
    logic [31:0] row_sum_next;
    if (!rst_n) begin
      sm_state         <= SM_IDLE;
      sm_row_idx       <= 5'd0;
      sm_col_idx       <= 5'd0;
      sm_row_sum_acc   <= 32'd0;
      sm_shifted_pipe  <= FP32_ZERO_BITS;
      sm_p_pipe        <= FP32_ZERO_BITS;
      sm_corr_shift_pipe <= FP32_ZERO_BITS;
      sm_l_corr_product <= FP32_ZERO_BITS;
      sm_masked_pipe   <= 1'b1;
      sm_scale_valid   <= 1'b0;
      sm_scale_row_pipe <= 5'd0;
      sm_scale_col_pipe <= 5'd0;
      sm_scale_value_pipe <= FP32_NEG_INF_BITS;
      sm_scale_masked_pipe <= 1'b1;
      sm_p_shift_valid <= 1'b0;
      sm_p_shift_row <= 5'd0;
      sm_p_shift_col <= 5'd0;
      sm_exp_quant_valid <= 1'b0;
      sm_exp_quant_row <= 5'd0;
      sm_exp_quant_col <= 5'd0;
      sm_exp_quant <= '0;
      sm_exp_req_valid <= 1'b0;
      sm_exp_req_row <= 5'd0;
      sm_exp_req_col <= 5'd0;
      sm_exp_req <= '0;
      sm_exp_lut_valid <= 1'b0;
      sm_exp_lut_row <= 5'd0;
      sm_exp_lut_col <= 5'd0;
      sm_exp_lut_mode <= 2'd0;
      sm_exp_lut_idx <= 10'd0;
      sm_exp_lut_rem <= 26'd0;
      sm_exp_frac_valid <= 1'b0;
      sm_exp_frac_row <= 5'd0;
      sm_exp_frac_col <= 5'd0;
      sm_exp_frac_mode <= 2'd0;
      sm_exp_frac_fp <= FP32_ZERO_BITS;
      sm_exp_frac_lut_lo <= FP32_ZERO_BITS;
      sm_exp_frac_lut_hi <= FP32_ZERO_BITS;
      sm_exp_delta_valid <= 1'b0;
      sm_exp_delta_row <= 5'd0;
      sm_exp_delta_col <= 5'd0;
      sm_exp_delta_mode <= 2'd0;
      sm_exp_delta_frac_fp <= FP32_ZERO_BITS;
      sm_exp_delta_lut_lo <= FP32_ZERO_BITS;
      sm_exp_delta <= FP32_ZERO_BITS;
      sm_exp_mul_valid <= 1'b0;
      sm_exp_mul_row <= 5'd0;
      sm_exp_mul_col <= 5'd0;
      sm_exp_mul_mode <= 2'd0;
      sm_exp_mul_lut_lo <= FP32_ZERO_BITS;
      sm_exp_mul_product <= FP32_ZERO_BITS;
      sm_p_lookup_valid <= 1'b0;
      sm_p_lookup_row <= 5'd0;
      sm_p_lookup_col <= 5'd0;
      sm_p_issue_done <= 1'b0;
      s_valid_r        <= 1'b0;
      kv_tile_first_r  <= 1'b0;
      causal_mask_en_r <= 1'b0;
      q_tile_start_r   <= 16'd0;
      kv_tile_start_r  <= 16'd0;
      active_rows_r    <= 5'd0;
      active_cols_r    <= 5'd0;
      p_valid          <= 1'b0;
      done             <= 1'b0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        sm_m_old[ri]    <= FP32_NEG_INF_BITS;
        sm_l_old[ri]    <= FP32_ZERO_BITS;
        sm_row_max[ri]  <= FP32_NEG_INF_BITS;
        sm_m_new[ri]    <= FP32_NEG_INF_BITS;
        sm_l_new[ri]    <= FP32_ZERO_BITS;
        sm_corr[ri]     <= FP32_ZERO_BITS;
        sm_row_sum[ri]  <= FP32_ZERO_BITS;
        m_state[ri]     <= 32'hFF80_0000;
        l_state[ri]     <= 32'd0;
        correction[ri]  <= 32'd0;
        for (ci = 0; ci < TILE_COLS; ci++) begin
          s_data_r[ri][ci] <= 32'd0;
          if (!SOFTMAX_SCORE_INPLACE)
            sm_scaled[ri][ci] <= 32'd0;
          sm_masked[ri][ci] <= 1'b1;
          sm_p[ri][ci]      <= 32'd0;
          p_data_reg[ri][ci] <= 32'd0;
        end
      end
    end else begin
      p_valid <= 1'b0;
      done    <= 1'b0;

      if (state_load) begin
        sm_state   <= SM_IDLE;
        s_valid_r <= 1'b0;
        sm_scale_valid <= 1'b0;
        sm_p_shift_valid <= 1'b0;
        sm_exp_quant_valid <= 1'b0;
        sm_exp_req_valid <= 1'b0;
        sm_exp_lut_valid <= 1'b0;
        sm_exp_frac_valid <= 1'b0;
        sm_exp_delta_valid <= 1'b0;
        sm_exp_mul_valid <= 1'b0;
        sm_p_lookup_valid <= 1'b0;
        sm_p_issue_done <= 1'b0;
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]    <= state_m_in[ri];
          l_state[ri]    <= state_l_in[ri];
          correction[ri] <= 32'd0;
        end
      end else begin
        unique case (sm_state)
          SM_IDLE: begin
            if (s_valid && s_ready) begin
              s_valid_r        <= 1'b1;
              kv_tile_first_r  <= kv_tile_first;
              causal_mask_en_r <= causal_mask_en;
              q_tile_start_r   <= q_tile_start;
              kv_tile_start_r  <= kv_tile_start;
              active_rows_r    <= active_rows;
              active_cols_r    <= active_cols;
              sm_row_idx       <= 5'd0;
              sm_col_idx       <= 5'd0;
              sm_row_sum_acc   <= 32'd0;
              sm_scale_valid   <= 1'b0;
              sm_state         <= SM_SCALE_MAX;
              for (ri = 0; ri < TILE_ROWS; ri++) begin
                sm_m_old[ri]   <= kv_tile_first ? FP32_NEG_INF_BITS : m_state[ri];
                sm_l_old[ri]   <= kv_tile_first ? FP32_ZERO_BITS    : l_state[ri];
                sm_row_max[ri] <= FP32_NEG_INF_BITS;
                sm_m_new[ri]   <= kv_tile_first ? FP32_NEG_INF_BITS : m_state[ri];
                sm_l_new[ri]   <= kv_tile_first ? FP32_ZERO_BITS    : l_state[ri];
                sm_corr[ri]    <= FP32_ZERO_BITS;
                sm_row_sum[ri] <= FP32_ZERO_BITS;
                for (ci = 0; ci < TILE_COLS; ci++) begin
                  s_data_r[ri][ci] <= s_data[ri][ci];
                end
              end
            end else begin
              s_valid_r <= 1'b0;
            end
          end

          SM_SCALE_MAX: begin
            row_valid = (sm_row_idx < active_rows_r);
            col_valid = (sm_col_idx < active_cols_r);
            masked    = !row_valid || !col_valid;
            scaled_val = FP32_NEG_INF_BITS;
            if (row_valid && col_valid)
              scaled_val = fp32_mul(s_data_r[sm_row_idx][sm_col_idx], INV_SQRT_D_FP32);
            if (row_valid && col_valid && causal_mask_en_r) begin
              q_pos = integer'(q_tile_start_r) + integer'(sm_row_idx);
              kv_pos = integer'(kv_tile_start_r) + integer'(sm_col_idx);
              if (q_pos < kv_pos) begin
                masked = 1'b1;
                scaled_val = FP32_NEG_INF_BITS;
              end
            end

            if (SOFTMAX_SCALE_PIPE) begin
              // Issue one scale operation per cycle and commit the previous
              // result to the row maximum.  This removes the dynamic score
              // mux + DSP multiply + fp32 compare chain from one cycle while
              // preserving one-element-per-cycle throughput.
              if (sm_scale_valid) begin
                if (SOFTMAX_SCORE_INPLACE)
                  s_data_r[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_value_pipe;
                else
                  sm_scaled[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_value_pipe;
                sm_masked[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_masked_pipe;
                row_max_next = fp32_max(sm_row_max[sm_scale_row_pipe], sm_scale_value_pipe);
                sm_row_max[sm_scale_row_pipe] <= row_max_next;
              end
              sm_scale_valid       <= 1'b1;
              sm_scale_row_pipe    <= sm_row_idx;
              sm_scale_col_pipe    <= sm_col_idx;
              sm_scale_value_pipe  <= scaled_val;
              sm_scale_masked_pipe <= masked;
            end else begin
              // One-click rollback to the signed-off v2.5 Phase 1 schedule.
              if (SOFTMAX_SCORE_INPLACE)
                s_data_r[sm_row_idx][sm_col_idx] <= scaled_val;
              else
                sm_scaled[sm_row_idx][sm_col_idx] <= scaled_val;
              sm_masked[sm_row_idx][sm_col_idx] <= masked;
              row_max_next = fp32_max(sm_row_max[sm_row_idx], scaled_val);
              sm_row_max[sm_row_idx] <= row_max_next;
            end

            if (sm_col_idx == SM_TILE_COLS_LAST) begin
              if (sm_row_idx == SM_TILE_ROWS_LAST) begin
                sm_row_idx <= 5'd0;
                sm_col_idx <= 5'd0;
                sm_state <= SOFTMAX_SCALE_PIPE ? SM_SCALE_DRAIN : SM_MAX_UPDATE;
              end else begin
                sm_row_idx <= sm_row_idx + 5'd1;
                sm_col_idx <= 5'd0;
              end
            end else begin
              sm_col_idx <= sm_col_idx + 5'd1;
            end
          end

          SM_SCALE_DRAIN: begin
            // Commit the final issued element before the max-update pass.
            if (sm_scale_valid) begin
              if (SOFTMAX_SCORE_INPLACE)
                s_data_r[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_value_pipe;
              else
                sm_scaled[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_value_pipe;
              sm_masked[sm_scale_row_pipe][sm_scale_col_pipe] <= sm_scale_masked_pipe;
              row_max_next = fp32_max(sm_row_max[sm_scale_row_pipe], sm_scale_value_pipe);
              sm_row_max[sm_scale_row_pipe] <= row_max_next;
            end
            sm_scale_valid <= 1'b0;
            sm_row_idx <= 5'd0;
            sm_col_idx <= 5'd0;
            sm_state <= SM_MAX_UPDATE;
          end

          SM_MAX_UPDATE: begin
            if (sm_row_idx < active_rows_r)
              sm_m_new[sm_row_idx] <= fp32_max(sm_m_old[sm_row_idx], sm_row_max[sm_row_idx]);
            else
              sm_m_new[sm_row_idx] <= sm_m_old[sm_row_idx];
            sm_state <= SM_CORR_SHIFT;
          end

          SM_CORR_SHIFT: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r))
              sm_corr_shift_pipe <= FP32_ZERO_BITS;
            else
              sm_corr_shift_pipe <= fp32_sub(sm_m_old[sm_row_idx], sm_m_new[sm_row_idx]);
            sm_state <= SM_CORR_LOOKUP;
          end

          SM_CORR_LOOKUP: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r)) begin
              sm_corr[sm_row_idx] <= FP32_ZERO_BITS;
              if (sm_row_idx == SM_TILE_ROWS_LAST) begin
                sm_row_idx <= 5'd0;
                sm_col_idx <= 5'd0;
                sm_row_sum_acc <= FP32_ZERO_BITS;
                sm_p_shift_valid <= 1'b0;
                sm_exp_quant_valid <= 1'b0;
                sm_exp_req_valid <= 1'b0;
                sm_exp_lut_valid <= 1'b0;
                sm_exp_frac_valid <= 1'b0;
                sm_exp_delta_valid <= 1'b0;
                sm_exp_mul_valid <= 1'b0;
                sm_p_lookup_valid <= 1'b0;
                sm_p_issue_done <= 1'b0;
`ifdef LARA_SOFTMAX_P_PIPE_ROLLBACK
                sm_state <= SM_P_SHIFT;
`else
                sm_state <= SM_P_PIPE;
`endif
              end else begin
                sm_row_idx <= sm_row_idx + 5'd1;
                sm_state <= SM_MAX_UPDATE;
              end
            end else begin
              sm_exp_quant <= exp_lookup_quantize(sm_corr_shift_pipe);
              sm_state <= SM_CORR_INDEX;
            end
          end

          // Correction EXP follows the same exact contract as the P EXP
          // pipeline, but is serialized per row and therefore uses explicit
          // FSM stages instead of valid-tag streaming.
          SM_CORR_INDEX: begin
            sm_exp_req <= exp_lookup_index(sm_exp_quant);
            sm_state <= SM_CORR_LUT;
          end

          SM_CORR_LUT: begin
            sm_exp_lut_mode <= sm_exp_req[37:36];
            sm_exp_lut_idx <= sm_exp_req[35:26];
            sm_exp_lut_rem <= sm_exp_req[25:0];
            if (sm_exp_req[37:36] == 2'd2) begin
              if (sm_exp_req[35:26] == LUT_DEPTH - 1)
                sm_exp_frac_mode <= 2'd3;
              else
                sm_exp_frac_mode <= 2'd2;
              sm_exp_frac_fp <= q26_to_fp32(
                  longint'(sm_exp_req[25:0])
              );
              sm_exp_frac_lut_lo <= exp_lut[sm_exp_req[35:26]];
              if (sm_exp_req[35:26] == LUT_DEPTH - 1)
                sm_exp_frac_lut_hi <= exp_lut[sm_exp_req[35:26]];
              else
                sm_exp_frac_lut_hi <= exp_lut[sm_exp_req[35:26] + 1'b1];
            end else begin
              sm_exp_frac_mode <= sm_exp_req[37:36];
              sm_exp_frac_fp <= FP32_ZERO_BITS;
              sm_exp_frac_lut_lo <= FP32_ZERO_BITS;
              sm_exp_frac_lut_hi <= FP32_ZERO_BITS;
            end
            sm_state <= SM_CORR_DELTA;
          end

          SM_CORR_DELTA: begin
            sm_exp_delta_mode <= sm_exp_frac_mode;
            sm_exp_delta_frac_fp <= sm_exp_frac_fp;
            sm_exp_delta_lut_lo <= sm_exp_frac_lut_lo;
            if (sm_exp_frac_mode == 2'd2)
              sm_exp_delta <= fp32_sub(
                  sm_exp_frac_lut_hi, sm_exp_frac_lut_lo
              );
            else
              sm_exp_delta <= FP32_ZERO_BITS;
            sm_state <= SM_CORR_MUL;
          end

          SM_CORR_MUL: begin
            sm_exp_mul_mode <= sm_exp_delta_mode;
            sm_exp_mul_lut_lo <= sm_exp_delta_lut_lo;
            if (sm_exp_delta_mode == 2'd2)
              sm_exp_mul_product <= fp32_mul(
                  sm_exp_delta, sm_exp_delta_frac_fp
              );
            else
              sm_exp_mul_product <= FP32_ZERO_BITS;
            sm_state <= SM_CORR_ADD;
          end

          SM_CORR_ADD: begin
            case (sm_exp_mul_mode)
              2'd0: sm_corr[sm_row_idx] <= FP32_ZERO_BITS;
              2'd1: sm_corr[sm_row_idx] <= FP32_ONE_BITS;
              2'd3: sm_corr[sm_row_idx] <= sm_exp_mul_lut_lo;
              default: sm_corr[sm_row_idx] <= fp32_add(
                  sm_exp_mul_lut_lo, sm_exp_mul_product
              );
            endcase

            if (sm_row_idx == SM_TILE_ROWS_LAST) begin
              sm_row_idx <= 5'd0;
              sm_col_idx <= 5'd0;
              sm_row_sum_acc <= FP32_ZERO_BITS;
              sm_p_shift_valid <= 1'b0;
              sm_exp_quant_valid <= 1'b0;
              sm_exp_req_valid <= 1'b0;
              sm_exp_lut_valid <= 1'b0;
              sm_exp_frac_valid <= 1'b0;
              sm_exp_delta_valid <= 1'b0;
              sm_exp_mul_valid <= 1'b0;
              sm_p_lookup_valid <= 1'b0;
              sm_p_issue_done <= 1'b0;
`ifdef LARA_SOFTMAX_P_PIPE_ROLLBACK
              sm_state <= SM_P_SHIFT;
`else
              sm_state <= SM_P_PIPE;
`endif
            end else begin
              sm_row_idx <= sm_row_idx + 5'd1;
              sm_state <= SM_MAX_UPDATE;
            end
          end

          SM_P_PIPE: begin
            // Commit EXP output and preserve the legacy left-to-right
            // fp32 row-sum recurrence.  Draining at every row boundary avoids
            // a cross-row dependency while still issuing one element/cycle.
            if (sm_p_lookup_valid) begin
              if (SOFTMAX_P_INPLACE) begin
                if (SOFTMAX_SCORE_INPLACE)
                  s_data_r[sm_p_lookup_row][sm_p_lookup_col] <= sm_p_pipe;
                else
                  sm_scaled[sm_p_lookup_row][sm_p_lookup_col] <= sm_p_pipe;
              end else begin
                sm_p[sm_p_lookup_row][sm_p_lookup_col] <= sm_p_pipe;
              end
              row_sum_next = fp32_add(sm_row_sum_acc, sm_p_pipe);
              sm_row_sum_acc <= row_sum_next;
              if (sm_p_lookup_col == SM_TILE_COLS_LAST) begin
                sm_row_sum[sm_p_lookup_row] <= row_sum_next;
                sm_row_sum_acc <= FP32_ZERO_BITS;
                sm_p_lookup_valid <= 1'b0;
                sm_p_issue_done <= 1'b0;
                sm_col_idx <= 5'd0;
                if (sm_p_lookup_row == SM_TILE_ROWS_LAST) begin
                  sm_row_idx <= 5'd0;
                  sm_state <= SM_L_MUL;
                end else begin
                  sm_row_idx <= sm_p_lookup_row + 5'd1;
                end
              end
            end

            // Stage 7: retire the final interpolation result.  The row/column
            // tags keep the left-to-right row-sum recurrence unchanged.
            sm_p_lookup_valid <= sm_exp_mul_valid;
            if (sm_exp_mul_valid) begin
              sm_p_lookup_row <= sm_exp_mul_row;
              sm_p_lookup_col <= sm_exp_mul_col;
              case (sm_exp_mul_mode)
                2'd0: sm_p_pipe <= FP32_ZERO_BITS;
                2'd1: sm_p_pipe <= FP32_ONE_BITS;
                2'd3: sm_p_pipe <= sm_exp_mul_lut_lo;
                default: sm_p_pipe <= fp32_add(
                    sm_exp_mul_lut_lo, sm_exp_mul_product
                );
              endcase
            end

            // Stage 6: multiply the exact LUT delta by the exact Q8.26
            // fraction.  This is deliberately separate from FP32 add.
            sm_exp_mul_valid <= sm_exp_delta_valid;
            if (sm_exp_delta_valid) begin
              sm_exp_mul_row <= sm_exp_delta_row;
              sm_exp_mul_col <= sm_exp_delta_col;
              sm_exp_mul_mode <= sm_exp_delta_mode;
              sm_exp_mul_lut_lo <= sm_exp_delta_lut_lo;
              if (sm_exp_delta_mode == 2'd2)
                sm_exp_mul_product <= fp32_mul(
                    sm_exp_delta, sm_exp_delta_frac_fp
                );
              else
                sm_exp_mul_product <= FP32_ZERO_BITS;
            end

            // Stage 5: calculate the exact LUT delta.  The original LUT
            // ordering and FP32 subtraction are preserved.
            sm_exp_delta_valid <= sm_exp_frac_valid;
            if (sm_exp_frac_valid) begin
              sm_exp_delta_row <= sm_exp_frac_row;
              sm_exp_delta_col <= sm_exp_frac_col;
              sm_exp_delta_mode <= sm_exp_frac_mode;
              sm_exp_delta_frac_fp <= sm_exp_frac_fp;
              sm_exp_delta_lut_lo <= sm_exp_frac_lut_lo;
              if (sm_exp_frac_mode == 2'd2)
                sm_exp_delta <= fp32_sub(
                    sm_exp_frac_lut_hi, sm_exp_frac_lut_lo
                );
              else
                sm_exp_delta <= FP32_ZERO_BITS;
            end

            // Stage 4: convert the Q8.26 remainder to FP32 and read the
            // adjacent LUT entries.  These values feed the delta stage.
            sm_exp_frac_valid <= sm_exp_lut_valid;
            if (sm_exp_lut_valid) begin
              sm_exp_frac_row <= sm_exp_lut_row;
              sm_exp_frac_col <= sm_exp_lut_col;
              if (sm_exp_lut_mode == 2'd2) begin
                // Preserve the original idx==1023 fast path exactly:
                // exp_lookup_bits returns the last ROM word directly,
                // without an FP32 add with zero.
                if (sm_exp_lut_idx == LUT_DEPTH - 1)
                  sm_exp_frac_mode <= 2'd3;
                else
                  sm_exp_frac_mode <= 2'd2;
                sm_exp_frac_fp <= q26_to_fp32(
                    longint'(sm_exp_lut_rem)
                );
                sm_exp_frac_lut_lo <= exp_lut[sm_exp_lut_idx];
                if (sm_exp_lut_idx == LUT_DEPTH - 1)
                  sm_exp_frac_lut_hi <= exp_lut[sm_exp_lut_idx];
                else
                  sm_exp_frac_lut_hi <= exp_lut[sm_exp_lut_idx + 1'b1];
              end else begin
                sm_exp_frac_mode <= sm_exp_lut_mode;
                sm_exp_frac_fp <= FP32_ZERO_BITS;
                sm_exp_frac_lut_lo <= FP32_ZERO_BITS;
                sm_exp_frac_lut_hi <= FP32_ZERO_BITS;
              end
            end

            // Stage 3: register the exact LUT request before any LUT read or
            // interpolation arithmetic.
            sm_exp_lut_valid <= sm_exp_req_valid;
            if (sm_exp_req_valid) begin
              sm_exp_lut_row <= sm_exp_req_row;
              sm_exp_lut_col <= sm_exp_req_col;
              sm_exp_lut_mode <= sm_exp_req[37:36];
              sm_exp_lut_idx <= sm_exp_req[35:26];
              sm_exp_lut_rem <= sm_exp_req[25:0];
            end

            // Stage 2: calculate the exact LUT index and Q8.26 remainder.
            sm_exp_req_valid <= sm_exp_quant_valid;
            if (sm_exp_quant_valid) begin
              sm_exp_req_row <= sm_exp_quant_row;
              sm_exp_req_col <= sm_exp_quant_col;
              sm_exp_req <= exp_lookup_index(sm_exp_quant);
            end

            // Stage 1: quantize the shifted FP32 value and preserve its mode.
            sm_exp_quant_valid <= sm_p_shift_valid;
            if (sm_p_shift_valid) begin
              sm_exp_quant_row <= sm_p_shift_row;
              sm_exp_quant_col <= sm_p_shift_col;
              if (sm_masked_pipe)
                sm_exp_quant <= {2'd0, 28'd0};
              else
                sm_exp_quant <= exp_lookup_quantize(sm_shifted_pipe);
            end

            // Stage 0: subtract the new row max and register its row/column tag.
            if (!sm_p_issue_done) begin
              sm_p_shift_valid <= 1'b1;
              sm_p_shift_row <= sm_row_idx;
              sm_p_shift_col <= sm_col_idx;
              sm_masked_pipe <= sm_masked[sm_row_idx][sm_col_idx];
              if (sm_masked[sm_row_idx][sm_col_idx])
                sm_shifted_pipe <= FP32_ZERO_BITS;
              else
                sm_shifted_pipe <= fp32_sub(
                    SOFTMAX_SCORE_INPLACE ? s_data_r[sm_row_idx][sm_col_idx]
                                          : sm_scaled[sm_row_idx][sm_col_idx],
                    sm_m_new[sm_row_idx]);

              if (sm_col_idx == SM_TILE_COLS_LAST)
                sm_p_issue_done <= 1'b1;
              else
                sm_col_idx <= sm_col_idx + 5'd1;
            end else begin
              sm_p_shift_valid <= 1'b0;
            end
          end

`ifdef LARA_SOFTMAX_P_PIPE_ROLLBACK
          SM_P_SHIFT: begin
            sm_masked_pipe <= sm_masked[sm_row_idx][sm_col_idx];
            if (sm_masked[sm_row_idx][sm_col_idx])
              sm_shifted_pipe <= FP32_ZERO_BITS;
            else
              sm_shifted_pipe <= fp32_sub(
                  SOFTMAX_SCORE_INPLACE ? s_data_r[sm_row_idx][sm_col_idx]
                                        : sm_scaled[sm_row_idx][sm_col_idx],
                  sm_m_new[sm_row_idx]);
            sm_state <= SM_P_LOOKUP;
          end

          SM_P_LOOKUP: begin
            if (sm_masked_pipe)
              sm_p_pipe <= FP32_ZERO_BITS;
            else
              sm_p_pipe <= exp_lookup_bits(sm_shifted_pipe);
            sm_state <= SM_P_ACCUM;
          end

          SM_P_ACCUM: begin
            if (SOFTMAX_P_INPLACE) begin
              if (SOFTMAX_SCORE_INPLACE)
                s_data_r[sm_row_idx][sm_col_idx] <= sm_p_pipe;
              else
                sm_scaled[sm_row_idx][sm_col_idx] <= sm_p_pipe;
            end else begin
              sm_p[sm_row_idx][sm_col_idx] <= sm_p_pipe;
            end
            row_sum_next = fp32_add(sm_row_sum_acc, sm_p_pipe);

            if (sm_col_idx == SM_TILE_COLS_LAST) begin
              sm_row_sum[sm_row_idx] <= row_sum_next;

              if (sm_row_idx == SM_TILE_ROWS_LAST) begin
                sm_row_idx <= 5'd0;
                sm_col_idx <= 5'd0;
                sm_state <= SM_L_MUL;
              end else begin
                sm_row_idx <= sm_row_idx + 5'd1;
                sm_col_idx <= 5'd0;
                sm_row_sum_acc <= FP32_ZERO_BITS;
                sm_state <= SM_P_SHIFT;
              end
            end else begin
              sm_col_idx <= sm_col_idx + 5'd1;
              sm_row_sum_acc <= row_sum_next;
              sm_state <= SM_P_SHIFT;
            end
          end
`endif

          SM_L_MUL: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r))
              sm_l_corr_product <= FP32_ZERO_BITS;
            else
              sm_l_corr_product <= fp32_mul(sm_l_old[sm_row_idx], sm_corr[sm_row_idx]);
            sm_state <= SM_L_ADD;
          end

          SM_L_ADD: begin
            if (sm_row_idx >= active_rows_r)
              sm_l_new[sm_row_idx] <= sm_l_old[sm_row_idx];
            else if (kv_tile_first_r)
              sm_l_new[sm_row_idx] <= sm_row_sum[sm_row_idx];
            else
              sm_l_new[sm_row_idx] <= fp32_add(sm_l_corr_product, sm_row_sum[sm_row_idx]);

            if (sm_row_idx == SM_TILE_ROWS_LAST) begin
              sm_state <= SM_WRITE;
            end else begin
              sm_row_idx <= sm_row_idx + 5'd1;
              sm_state <= SM_L_MUL;
            end
          end

          SM_WRITE: begin
            p_valid <= 1'b1;
            done    <= 1'b1;
            s_valid_r <= 1'b0;
            for (ri = 0; ri < TILE_ROWS; ri++) begin
              m_state[ri]    <= sm_m_new[ri];
              l_state[ri]    <= sm_l_new[ri];
              correction[ri] <= sm_corr[ri];
              for (ci = 0; ci < TILE_COLS; ci++) begin
                if (SOFTMAX_P_INPLACE) begin
                  if (SOFTMAX_SCORE_INPLACE)
                    p_data_reg[ri][ci] <= s_data_r[ri][ci];
                  else
                    p_data_reg[ri][ci] <= sm_scaled[ri][ci];
                end else begin
                  p_data_reg[ri][ci] <= sm_p[ri][ci];
                end
              end
            end
            sm_state <= SM_IDLE;
          end

          default: begin
            sm_state <= SM_IDLE;
          end
        endcase
      end
    end
  end
`endif

endmodule
