// ============================================================================
// softmax_engine.sv — Online Softmax Hardware Engine
// ============================================================================
// Computes attention weights P = softmax(S/√d) using FlashAttention's
// online softmax algorithm. Maintains running state (m, l) across KV tiles.
//
// Algorithm (per row i, TILE_ROWS=16 parallel):
//   1. Scale:  S_scaled = S_block / sqrt(HEAD_DIM)            [fp32 multiply]
//   2. RowMax: row_max = max(S_scaled across TILE_COLS)       [reduction tree]
//   3. Update: m_new = max(m_old, row_max)
//   4. Correct: correction = exp(m_old - m_new)              [EXP LUT, 1 cycle]
//   5. P:      P = exp(S_scaled - m_new)                     [EXP LUT, 1 cycle]
//   6. RowSum: row_sum = sum(P across TILE_COLS)             [reduction tree]
//   7. Update: l_new = l_old * correction + row_sum
//   8. Output: P_tile valid (streamed to MAC Phase B)
//
// EXP LUT: 1024-entry fp32 ROM, [-8, 0] range, linear interpolation.
//   Precision: < 0.1% relative error.
//   Resource: 1 BRAM (18Kb).
//
// Correspondence with Golden Model:
//   Python: attention_golden.py::OnlineSoftmaxState
//   Python: attention_golden.py::build_exp_lut(), exp_lut_lookup()
//
// VCS compatibility: Uses integer (not int) for all always_ff loop variables.
// ============================================================================

module softmax_engine
  import attn_pkg::*;
(
    input  logic                           clk,
    input  logic                           rst_n,

    // --- S_tile Input (from MAC Phase A) ---
    input  logic                           s_valid,
    input  logic [FP32_W-1:0]              s_data [TILE_ROWS][TILE_COLS],

    // --- Control ---
    input  logic                           kv_tile_first,  // init m/l for new Q tile
    input  logic                           kv_tile_last,   // trigger final norm

    // --- Causal Masking (decoder-only autoregressive) ---
    input  logic                           causal_mask_en, // enable causal masking
    input  logic [15:0]                    q_tile_start,   // absolute Q row start index
    input  logic [15:0]                    kv_tile_start,  // absolute K col start index
    input  logic [4:0]                     active_rows,    // valid rows in this 16x16 block
    input  logic [4:0]                     active_cols,    // valid cols in this 16x16 block

    // --- Optional State Context Load (for time-multiplexed microtiles) ---
    input  logic                           state_load,
    input  logic [FP32_W-1:0]              state_m_in [TILE_ROWS],
    input  logic [FP32_W-1:0]              state_l_in [TILE_ROWS],

    // --- Running State (maintained across KV tiles) ---
    output logic [FP32_W-1:0]              m_state [TILE_ROWS],   // running max per row
    output logic [FP32_W-1:0]              l_state [TILE_ROWS],   // running sum per row

    // --- P_tile Output (to MAC Phase B) ---
    output logic                           p_valid,
    output logic [FP32_W-1:0]              p_data [TILE_ROWS][TILE_COLS],

    // --- Correction factors (to psum_accum for O_acc update) ---
    output logic [FP32_W-1:0]              correction [TILE_ROWS],

    // --- Done pulse ---
    output logic                           done
);

  (* keep = "true" *) logic unused_kv_tile_last;
  assign unused_kv_tile_last = &{1'b0, kv_tile_last};

  // ==================================================================
  // EXP LUT ROM (1024 × fp32)
  // ==================================================================
  // Generated by Python golden model: build_exp_lut()
  // Range: [-8.0, 0.0], 1024 entries, linear interpolation between entries.
  //
  // For synthesis: infer as BRAM ROM (read-only, initialized at bitstream load).
  // For simulation: loaded from $readmemh or generated inline.

  localparam int LUT_DEPTH = 1024;
  localparam logic [31:0] FP32_NEG_INF_BITS = 32'hFF80_0000;
  localparam logic [31:0] FP32_ZERO_BITS    = 32'h0000_0000;
  localparam logic [15:0] BF16_INV_SQRT_D_BITS = INV_SQRT_D_FP32[31:16];
  localparam shortreal NEG_INF_SR    = -1.0e30;
  localparam shortreal NEG_EIGHT_SR  = -8.0;
  localparam shortreal ZERO_SR       = 0.0;
  localparam shortreal ONE_SR        = 1.0;
  localparam shortreal EIGHT_SR      = 8.0;
  (* rom_style = "block" *) logic [FP32_W-1:0] exp_lut [0:LUT_DEPTH-1];

`ifndef SYNTHESIS
  // LUT initialization for simulation. Try the local TB path first, then the
  // repo-relative path used by direct module compiles.
  initial begin
    integer fd;
    integer lut_scan_rc;
    lut_scan_rc = 0;
    fd = $fopen("data/exp_lut.hex", "r");
    if (fd == 0)
      fd = $fopen("VV/data/exp_lut.hex", "r");
    if (fd != 0) begin
      for (int li = 0; li < LUT_DEPTH; li++)
        lut_scan_rc = $fscanf(fd, "%h", exp_lut[li]);
      $fclose(fd);
    end else begin
      $display("WARNING: exp_lut.hex not found. Expected data/exp_lut.hex or VV/data/exp_lut.hex");
      $display("  python python_godel/attention_golden.py --export-tb-data --module softmax");
    end
  end
`else
  // Vivado can infer ROM contents from a direct readmemh on a project-added
  // memory-init file. Avoid fopen/fscanf, which synthesis ignores.
  initial begin
    $readmemh("exp_lut.hex", exp_lut);
  end
`endif

  // ==================================================================
  // EXP LUT Lookup Function
  // ==================================================================
  // Input:  x in fp32, range [-8, 0] (clamped outside)
  // Output: exp(x) in fp32
  // Latency: 1 cycle (combinational lookup + interpolation)
  function automatic shortreal exp_lookup(input shortreal x);
    /* verilator lint_off WIDTHEXPAND */
    shortreal x_clamped;
    shortreal idx_float, frac;
    integer idx_lo, idx_hi;
    shortreal v_lo, v_hi;

    // Clamp to [-8, 0]
    if (x < NEG_EIGHT_SR)      x_clamped = NEG_EIGHT_SR;
    else if (x > ZERO_SR)      x_clamped = ZERO_SR;
    else               x_clamped = x;

    // Map [-8, 0] → [0, 1023]
    idx_float = (x_clamped + EIGHT_SR) * shortreal'(LUT_DEPTH - 1) / EIGHT_SR;
    idx_lo = integer'(idx_float);
    idx_hi = idx_lo + 1;
    if (idx_hi >= LUT_DEPTH) idx_hi = LUT_DEPTH - 1;

    frac = idx_float - shortreal'(idx_lo);

    v_lo = $bitstoshortreal(exp_lut[idx_lo]);
    v_hi = $bitstoshortreal(exp_lut[idx_hi]);

    // Linear interpolation
    exp_lookup = v_lo + frac * (v_hi - v_lo);
    /* verilator lint_on WIDTHEXPAND */
  endfunction

  // ==================================================================
  // Pipeline Registers
  // ==================================================================
  // Stage 1 → Stage 2 pipeline

  logic                           s_valid_r;
  logic [FP32_W-1:0]              s_data_r [TILE_ROWS][TILE_COLS];
  logic                           kv_tile_first_r;
  logic                           causal_mask_en_r;
  logic [15:0]                    q_tile_start_r, kv_tile_start_r;
  logic [4:0]                     active_rows_r, active_cols_r;

  // Stage 1 computed values
  shortreal row_max_s1   [TILE_ROWS];
  shortreal m_old_s1     [TILE_ROWS];
  shortreal S_scaled     [TILE_ROWS][TILE_COLS];

  // Stage 2 outputs
  shortreal P_shortreal  [TILE_ROWS][TILE_COLS];
  shortreal m_new        [TILE_ROWS];
  shortreal l_new        [TILE_ROWS];
  shortreal correction_s [TILE_ROWS];

  // ==================================================================
  // Stage 1: Scale + RowMax + Max Update
  // ==================================================================
  // Computes: S_scaled = S * (1/sqrt(HEAD_DIM)), row_max per row

  // sqrt(128) ≈ 11.3137, 1/sqrt(128) ≈ 0.088388 (from pkg: INV_SQRT_D_FP32)

`ifndef SYNTHESIS
  /* verilator lint_off SHORTREAL */
  /* verilator lint_off WIDTHEXPAND */
  /* verilator lint_off WIDTHTRUNC */
  always_comb begin
    integer ri, ci;
    integer active_rows_i, active_cols_i;
    logic row_valid, col_valid;
    active_rows_i = integer'(active_rows);
    active_cols_i = integer'(active_cols);
    for (ri = 0; ri < TILE_ROWS; ri++) begin
      row_valid = (ri < active_rows_i);
      row_max_s1[ri] = $bitstoshortreal(FP32_NEG_INF_BITS);
      for (ci = 0; ci < TILE_COLS; ci++) begin
        col_valid = (ci < active_cols_i);
        if (row_valid && col_valid) begin
          S_scaled[ri][ci] = $bitstoshortreal(s_data[ri][ci])
                           * $bitstoshortreal(INV_SQRT_D_FP32);
        end else begin
          S_scaled[ri][ci] = $bitstoshortreal(FP32_NEG_INF_BITS);
        end
        if (row_valid && col_valid && causal_mask_en) begin
          if ((q_tile_start + 16'(ri)) < (kv_tile_start + 16'(ci)))
            S_scaled[ri][ci] = $bitstoshortreal(FP32_NEG_INF_BITS);
        end
        if (S_scaled[ri][ci] > row_max_s1[ri])
          row_max_s1[ri] = S_scaled[ri][ci];
      end
    end
  end

  // ==================================================================
  // Pipeline Stage 1 → 2 (registered)
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      s_valid_r <= 1'b0;
      kv_tile_first_r <= 1'b0;
      causal_mask_en_r <= 1'b0;
      q_tile_start_r   <= 16'd0;
      kv_tile_start_r  <= 16'd0;
      active_rows_r    <= 5'd0;
      active_cols_r    <= 5'd0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= $bitstoshortreal(FP32_ZERO_BITS);
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= 32'd0;
      end
    end else begin
      s_valid_r <= s_valid;
      kv_tile_first_r <= kv_tile_first;
      causal_mask_en_r <= causal_mask_en;
      q_tile_start_r   <= q_tile_start;
      kv_tile_start_r  <= kv_tile_start;
      active_rows_r    <= active_rows;
      active_cols_r    <= active_cols;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_old_s1[ri] <= $bitstoshortreal(m_state[ri]);
        for (ci = 0; ci < TILE_COLS; ci++)
          s_data_r[ri][ci] <= s_data[ri][ci];
      end
    end
  end

  // ==================================================================
  // Stage 2: Online Softmax Update
  // ==================================================================
  // For each row: compute m_new, correction, P, l_new

  always_comb begin
    integer ri, ci;
    integer active_rows_i, active_cols_i;
    logic row_valid, col_valid;
    logic masked;
    shortreal m_old_val, row_max_val, m_new_val;
    shortreal correction_val, l_old_val;
    shortreal row_exp_sum, S_shifted, P_val;
    active_rows_i = integer'(active_rows_r);
    active_cols_i = integer'(active_cols_r);
    masked = 1'b1;
    S_shifted = ZERO_SR;
    P_val = ZERO_SR;

    for (ri = 0; ri < TILE_ROWS; ri++) begin
      row_valid = (ri < active_rows_i);
      m_old_val = m_old_s1[ri];
      row_max_val = row_max_s1[ri];
      m_new_val = m_old_val;
      correction_val = ONE_SR;
      row_exp_sum = ZERO_SR;

      // Init on first KV tile: m starts at -inf, l at 0
      if (s_valid_r && kv_tile_first_r) begin
        m_old_val = NEG_INF_SR;
        l_old_val = ZERO_SR;  // use local variable, not output port
      end else begin
        l_old_val = $bitstoshortreal(l_state[ri]);
      end

      correction_s[ri] = ONE_SR;
      m_new[ri] = m_old_val;
      l_new[ri] = l_old_val;
      for (ci = 0; ci < TILE_COLS; ci++)
        P_shortreal[ri][ci] = ZERO_SR;

      if (!row_valid) begin
        col_valid = 1'b0;
      end else begin
        // Update running max
        if (m_old_val > row_max_val)
          m_new_val = m_old_val;
        else
          m_new_val = row_max_val;

        // Correction factor: exp(m_old - m_new)
        if (s_valid_r && kv_tile_first_r)
          correction_val = ZERO_SR;
        else
          correction_val = exp_lookup(m_old_val - m_new_val);
        correction_s[ri] = correction_val;

        // Running max output
        m_new[ri] = m_new_val;

        // Compute P and row sum
        for (ci = 0; ci < TILE_COLS; ci++) begin
          S_shifted = ZERO_SR;
          P_val = ZERO_SR;
          masked = 1'b1;
          col_valid = (ci < active_cols_i);
          masked = !col_valid;
          S_shifted = $bitstoshortreal(s_data_r[ri][ci]) * $bitstoshortreal(INV_SQRT_D_FP32)
                      - m_new_val;

          // Causal masking: mask out future positions (q_pos < k_pos → -inf)
          if (causal_mask_en_r && col_valid) begin
            if ((q_tile_start_r + 16'(ri)) < (kv_tile_start_r + 16'(ci)))
              masked = 1'b1;
          end

          if (masked)
            P_val = ZERO_SR;
          else
            P_val = exp_lookup(S_shifted);
          P_shortreal[ri][ci] = P_val;
          row_exp_sum = row_exp_sum + P_val;
        end

        // Update running sum: l_new = l_old * correction + row_exp_sum
        if (s_valid_r && kv_tile_first_r)
          l_new[ri] = row_exp_sum;
        else
          l_new[ri] = l_old_val * correction_val + row_exp_sum;
      end
    end
  end

  // ==================================================================
  // Output Register Stage
  // ==================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    if (!rst_n) begin
      p_valid <= 1'b0;
      done    <= 1'b0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        m_state[ri]   <= 32'hFF800000;  // -inf in fp32
        l_state[ri]   <= 32'd0;
        correction[ri] <= 32'd0;
        for (ci = 0; ci < TILE_COLS; ci++)
          p_data[ri][ci] <= 32'd0;
      end
    end else begin
      p_valid <= s_valid_r;  // 2-cycle pipeline delay from s_valid
      done    <= s_valid_r;

      if (state_load) begin
        p_valid <= 1'b0;
        done    <= 1'b0;
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]   <= state_m_in[ri];
          l_state[ri]   <= state_l_in[ri];
          correction[ri] <= 32'd0;
        end
      end else if (s_valid_r) begin
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]   <= $shortrealtobits(m_new[ri]);
          l_state[ri]   <= $shortrealtobits(l_new[ri]);
          correction[ri] <= $shortrealtobits(correction_s[ri]);
          for (ci = 0; ci < TILE_COLS; ci++)
            p_data[ri][ci] <= $shortrealtobits(P_shortreal[ri][ci]);
        end
      end
    end
  end


  /* verilator lint_on WIDTHTRUNC */
  /* verilator lint_on WIDTHEXPAND */
  /* verilator lint_on SHORTREAL */
`else
  typedef enum logic [3:0] {
    SM_IDLE        = 4'd0,
    SM_SCALE_MAX   = 4'd1,
    SM_MAX_UPDATE  = 4'd2,
    SM_CORR_SHIFT  = 4'd3,
    SM_CORR_LOOKUP = 4'd4,
    SM_P_SHIFT     = 4'd5,
    SM_P_LOOKUP    = 4'd6,
    SM_P_ACCUM     = 4'd7,
    SM_L_MUL       = 4'd8,
    SM_L_ADD       = 4'd9,
    SM_WRITE       = 4'd10
  } sm_state_t;

  sm_state_t sm_state;
  logic [4:0] sm_row_idx;
  logic [4:0] sm_col_idx;
  logic [31:0] sm_row_sum_acc;
  logic [31:0] sm_row_sum [TILE_ROWS];
  logic [31:0] sm_shifted_pipe;
  logic [31:0] sm_p_pipe;
  logic [31:0] sm_corr_shift_pipe;
  logic [31:0] sm_l_corr_product;
  logic        sm_masked_pipe;
  localparam logic [4:0] SM_TILE_ROWS_LAST = 5'(TILE_ROWS - 1);
  localparam logic [4:0] SM_TILE_COLS_LAST = 5'(TILE_COLS - 1);
  logic [31:0] sm_m_old [TILE_ROWS];
  logic [31:0] sm_l_old [TILE_ROWS];
  logic [31:0] sm_row_max [TILE_ROWS];
  logic [31:0] sm_m_new [TILE_ROWS];
  logic [31:0] sm_l_new [TILE_ROWS];
  logic [31:0] sm_corr [TILE_ROWS];
  logic [31:0] sm_p [TILE_ROWS][TILE_COLS];
  logic [31:0] sm_scaled [TILE_ROWS][TILE_COLS];
  logic        sm_masked [TILE_ROWS][TILE_COLS];

  function automatic logic [31:0] exp_lookup_bits(input logic [31:0] x);
    logic signed [23:0] x_q;
    integer idx_num;
    integer idx;
    begin
      x_q = fp32_to_q8_15(x);
      if (x_q < -24'sd262144) x_q = -24'sd262144;
      else if (x_q > 24'sd0)  x_q = 24'sd0;

      idx_num = integer'(x_q) + 262144;
      // floor(idx_num * 1023 / 262144), without a constant multiplier.
      idx = (idx_num == 0) ? 0 : ((idx_num - 1) >>> 8);
      if (idx < 0) idx = 0;
      else if (idx >= LUT_DEPTH) idx = LUT_DEPTH - 1;
      exp_lookup_bits = exp_lut[idx];
    end
  endfunction

  always_ff @(posedge clk or negedge rst_n) begin
    integer ri, ci;
    logic        row_valid;
    logic        col_valid;
    logic        masked;
    integer      q_pos;
    integer      kv_pos;
    logic [31:0] scaled_val;
    logic [31:0] row_max_next;
    logic [31:0] row_sum_next;
    if (!rst_n) begin
      sm_state         <= SM_IDLE;
      sm_row_idx       <= 5'd0;
      sm_col_idx       <= 5'd0;
      sm_row_sum_acc   <= 32'd0;
      sm_shifted_pipe  <= FP32_ZERO_BITS;
      sm_p_pipe        <= FP32_ZERO_BITS;
      sm_corr_shift_pipe <= FP32_ZERO_BITS;
      sm_l_corr_product <= FP32_ZERO_BITS;
      sm_masked_pipe   <= 1'b1;
      s_valid_r        <= 1'b0;
      kv_tile_first_r  <= 1'b0;
      causal_mask_en_r <= 1'b0;
      q_tile_start_r   <= 16'd0;
      kv_tile_start_r  <= 16'd0;
      active_rows_r    <= 5'd0;
      active_cols_r    <= 5'd0;
      p_valid          <= 1'b0;
      done             <= 1'b0;
      for (ri = 0; ri < TILE_ROWS; ri++) begin
        sm_m_old[ri]    <= FP32_NEG_INF_BITS;
        sm_l_old[ri]    <= FP32_ZERO_BITS;
        sm_row_max[ri]  <= FP32_NEG_INF_BITS;
        sm_m_new[ri]    <= FP32_NEG_INF_BITS;
        sm_l_new[ri]    <= FP32_ZERO_BITS;
        sm_corr[ri]     <= FP32_ZERO_BITS;
        sm_row_sum[ri]  <= FP32_ZERO_BITS;
        m_state[ri]     <= 32'hFF80_0000;
        l_state[ri]     <= 32'd0;
        correction[ri]  <= 32'd0;
        for (ci = 0; ci < TILE_COLS; ci++) begin
          s_data_r[ri][ci] <= 32'd0;
          sm_scaled[ri][ci] <= 32'd0;
          sm_masked[ri][ci] <= 1'b1;
          sm_p[ri][ci]      <= 32'd0;
          p_data[ri][ci]    <= 32'd0;
        end
      end
    end else begin
      p_valid <= 1'b0;
      done    <= 1'b0;

      if (state_load) begin
        sm_state   <= SM_IDLE;
        s_valid_r <= 1'b0;
        for (ri = 0; ri < TILE_ROWS; ri++) begin
          m_state[ri]    <= state_m_in[ri];
          l_state[ri]    <= state_l_in[ri];
          correction[ri] <= 32'd0;
        end
      end else begin
        unique case (sm_state)
          SM_IDLE: begin
            if (s_valid) begin
              s_valid_r        <= 1'b1;
              kv_tile_first_r  <= kv_tile_first;
              causal_mask_en_r <= causal_mask_en;
              q_tile_start_r   <= q_tile_start;
              kv_tile_start_r  <= kv_tile_start;
              active_rows_r    <= active_rows;
              active_cols_r    <= active_cols;
              sm_row_idx       <= 5'd0;
              sm_col_idx       <= 5'd0;
              sm_row_sum_acc   <= 32'd0;
              sm_state         <= SM_SCALE_MAX;
              for (ri = 0; ri < TILE_ROWS; ri++) begin
                sm_m_old[ri]   <= kv_tile_first ? FP32_NEG_INF_BITS : m_state[ri];
                sm_l_old[ri]   <= kv_tile_first ? FP32_ZERO_BITS    : l_state[ri];
                sm_row_max[ri] <= FP32_NEG_INF_BITS;
                sm_m_new[ri]   <= kv_tile_first ? FP32_NEG_INF_BITS : m_state[ri];
                sm_l_new[ri]   <= kv_tile_first ? FP32_ZERO_BITS    : l_state[ri];
                sm_corr[ri]    <= FP32_ZERO_BITS;
                sm_row_sum[ri] <= FP32_ZERO_BITS;
                for (ci = 0; ci < TILE_COLS; ci++) begin
                  s_data_r[ri][ci] <= s_data[ri][ci];
                end
              end
            end else begin
              s_valid_r <= 1'b0;
            end
          end

          SM_SCALE_MAX: begin
            row_valid = (sm_row_idx < active_rows_r);
            col_valid = (sm_col_idx < active_cols_r);
            masked    = !row_valid || !col_valid;
            scaled_val = FP32_NEG_INF_BITS;
            if (row_valid && col_valid)
              scaled_val = bf16_mul_to_fp32(fp32_to_bf16(s_data_r[sm_row_idx][sm_col_idx]), BF16_INV_SQRT_D_BITS);
            if (row_valid && col_valid && causal_mask_en_r) begin
              q_pos = integer'(q_tile_start_r) + integer'(sm_row_idx);
              kv_pos = integer'(kv_tile_start_r) + integer'(sm_col_idx);
              if (q_pos < kv_pos) begin
                masked = 1'b1;
                scaled_val = FP32_NEG_INF_BITS;
              end
            end

            sm_scaled[sm_row_idx][sm_col_idx] <= scaled_val;
            sm_masked[sm_row_idx][sm_col_idx] <= masked;
            row_max_next = fp32_max(sm_row_max[sm_row_idx], scaled_val);
            sm_row_max[sm_row_idx] <= row_max_next;

            if (sm_col_idx == SM_TILE_COLS_LAST) begin
              if (sm_row_idx == SM_TILE_ROWS_LAST) begin
                sm_row_idx <= 5'd0;
                sm_col_idx <= 5'd0;
                sm_state <= SM_MAX_UPDATE;
              end else begin
                sm_row_idx <= sm_row_idx + 5'd1;
                sm_col_idx <= 5'd0;
              end
            end else begin
              sm_col_idx <= sm_col_idx + 5'd1;
            end
          end

          SM_MAX_UPDATE: begin
            if (sm_row_idx < active_rows_r)
              sm_m_new[sm_row_idx] <= fp32_max(sm_m_old[sm_row_idx], sm_row_max[sm_row_idx]);
            else
              sm_m_new[sm_row_idx] <= sm_m_old[sm_row_idx];
            sm_state <= SM_CORR_SHIFT;
          end

          SM_CORR_SHIFT: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r))
              sm_corr_shift_pipe <= FP32_ZERO_BITS;
            else
              sm_corr_shift_pipe <= fp32_sub(sm_m_old[sm_row_idx], sm_m_new[sm_row_idx]);
            sm_state <= SM_CORR_LOOKUP;
          end

          SM_CORR_LOOKUP: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r))
              sm_corr[sm_row_idx] <= FP32_ZERO_BITS;
            else
              sm_corr[sm_row_idx] <= exp_lookup_bits(sm_corr_shift_pipe);

            if (sm_row_idx == SM_TILE_ROWS_LAST) begin
              sm_row_idx <= 5'd0;
              sm_col_idx <= 5'd0;
              sm_row_sum_acc <= FP32_ZERO_BITS;
              sm_state <= SM_P_SHIFT;
            end else begin
              sm_row_idx <= sm_row_idx + 5'd1;
              sm_state <= SM_MAX_UPDATE;
            end
          end

          SM_P_SHIFT: begin
            sm_masked_pipe <= sm_masked[sm_row_idx][sm_col_idx];
            if (sm_masked[sm_row_idx][sm_col_idx])
              sm_shifted_pipe <= FP32_ZERO_BITS;
            else
              sm_shifted_pipe <= fp32_sub(sm_scaled[sm_row_idx][sm_col_idx], sm_m_new[sm_row_idx]);
            sm_state <= SM_P_LOOKUP;
          end

          SM_P_LOOKUP: begin
            if (sm_masked_pipe)
              sm_p_pipe <= FP32_ZERO_BITS;
            else
              sm_p_pipe <= exp_lookup_bits(sm_shifted_pipe);
            sm_state <= SM_P_ACCUM;
          end

          SM_P_ACCUM: begin
            sm_p[sm_row_idx][sm_col_idx] <= sm_p_pipe;
            row_sum_next = fp32_add(sm_row_sum_acc, sm_p_pipe);

            if (sm_col_idx == SM_TILE_COLS_LAST) begin
              sm_row_sum[sm_row_idx] <= row_sum_next;

              if (sm_row_idx == SM_TILE_ROWS_LAST) begin
                sm_row_idx <= 5'd0;
                sm_col_idx <= 5'd0;
                sm_state <= SM_L_MUL;
              end else begin
                sm_row_idx <= sm_row_idx + 5'd1;
                sm_col_idx <= 5'd0;
                sm_row_sum_acc <= FP32_ZERO_BITS;
                sm_state <= SM_P_SHIFT;
              end
            end else begin
              sm_col_idx <= sm_col_idx + 5'd1;
              sm_row_sum_acc <= row_sum_next;
              sm_state <= SM_P_SHIFT;
            end
          end

          SM_L_MUL: begin
            if (kv_tile_first_r || (sm_row_idx >= active_rows_r))
              sm_l_corr_product <= FP32_ZERO_BITS;
            else
              sm_l_corr_product <= fp32_mul(sm_l_old[sm_row_idx], sm_corr[sm_row_idx]);
            sm_state <= SM_L_ADD;
          end

          SM_L_ADD: begin
            if (sm_row_idx >= active_rows_r)
              sm_l_new[sm_row_idx] <= sm_l_old[sm_row_idx];
            else if (kv_tile_first_r)
              sm_l_new[sm_row_idx] <= sm_row_sum[sm_row_idx];
            else
              sm_l_new[sm_row_idx] <= fp32_add(sm_l_corr_product, sm_row_sum[sm_row_idx]);

            if (sm_row_idx == SM_TILE_ROWS_LAST) begin
              sm_state <= SM_WRITE;
            end else begin
              sm_row_idx <= sm_row_idx + 5'd1;
              sm_state <= SM_L_MUL;
            end
          end

          SM_WRITE: begin
            p_valid <= 1'b1;
            done    <= 1'b1;
            s_valid_r <= 1'b0;
            for (ri = 0; ri < TILE_ROWS; ri++) begin
              m_state[ri]    <= sm_m_new[ri];
              l_state[ri]    <= sm_l_new[ri];
              correction[ri] <= sm_corr[ri];
              for (ci = 0; ci < TILE_COLS; ci++)
                p_data[ri][ci] <= sm_p[ri][ci];
            end
            sm_state <= SM_IDLE;
          end

          default: begin
            sm_state <= SM_IDLE;
          end
        endcase
      end
    end
  end
`endif

endmodule
